name: Deploy
#trigger on push to main branch:
on:
  push:
    branches:
      - main
# trigger these jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #comes from github actions
      - uses: actions/checkout@v2
      #comes from a heroku deployed action
      - uses: hfang821/heroku-deploy@v3.12.11
      #required parameters
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "floating-hollows-67199"
          heroku_email: "kevin-fang@hotmail.ca"
